config/routes.rb
Rails.application.routes.draw do

  root 'photographies#index'

  resources :comments

  resources :photographies do
	  member do
	    put 'like', to: "photographies#like"
	    put 'unlike', to: "photographies#unlike"
	  end
  end

  get '/lenta' => 'photographies#lenta', as: :photography_lenta

  devise_for :users

  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :photography
	belongs_to :user
end

app/models/photography.rb
class Photography < ApplicationRecord
	
	has_attached_file :image,
					  styles: {medium: '300x300>', thumb: '100x100>'},
					  default_url: '/images/:style/missing.png'

	validates_attachment_content_type :image,
									  content_type: ['image/jpeg', 'image/gif', 'image/png']
	
	acts_as_votable
	
	belongs_to :user

	has_many :comments, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
  	validates :followed_id, presence: true
  	
end

app/models/user.rb
class User < ApplicationRecord

	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

	validates :name, presence: true, length: {maximum: 50}

	has_attached_file :avatar,
					  styles: {medium: '100x100>', thumb: '50x50>'},
					  default_url: '/images/:style/missing.png'

	validates_attachment_content_type :avatar,
									  content_type: ['image/jpeg', 'image/gif', 'image/png']

	has_many :photographies
	has_many :comments, dependent: :destroy
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy

	has_many :followed_users, through: :relationships, source: :followed

	def following?(other_user)
		relationships.find_by(followed_id: other_user)
		# relationships.find_by(followed_id: other_user.id)posle izmenenii ne srabotal
	end

	def follow!(other_user)
		relationships.create!(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		relationships.find_by(followed_id: other_user.id).destroy!
	end

	has_many :reverse_relationships, 
			 foreign_key: "followed_id", 
			 class_name: "Relationship", 
			 dependent: :destroy

	has_many :followers, through: :reverse_relationships, source: :follower

	acts_as_voter

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:edit, :update, :destroy]

  before_action :no_actions, only: [:edit, :update, :destroy]

  def create
  	@comment = Comment.new(comment_params)

  	if @comment.save
      redirect_to :back
  	end
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

    redirect_to :back
  end

  def edit
  end

  def update
  	if @comment.update(comment_params) 

		  redirect_to photography_path(@comment.photography.id)
  	else
  		render 'edit'
  	end
  end

  private

  def comment_params
  	params.require(:comment).permit(:title, :photography_id, :user_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end


  def no_actions
    unless current_user == @comment.user
        unless current_user == @comment.photography.user
          
        redirect_to root_path
        end
    end
  end

end

app/controllers/photographies_controller.rb
class PhotographiesController < ApplicationController

  before_filter :authenticate_user!, except: [:index]

  def index
    if user_signed_in?
      @photographies = current_user.photographies
    else
      @users = User.all
    end
  end

  def new
  	@photography = Photography.new
  end

  def create
  	@photography = Photography.new(photography_params)
  	if @photography.save
  		redirect_to photographies_path
  	else
  		render 'new'
  	end
  end

  def show
  	@photography = Photography.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all
  end

  def destroy
  	@photography = Photography.find(params[:id])
  	@photography.destroy

    redirect_to photographies_path
  end

  def lenta
    @users = User.all
    @photographies = Photography.all
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def like
    @photography = Photography.find(params[:id])
    @photography.liked_by current_user
    redirect_to :back
  end

  def unlike
    @photography = Photography.find(params[:id])
    @photography.unliked_by current_user
    redirect_to :back
  end

  private

  def photography_params
  	params.require(:photography).permit(:name, :image, :user_id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to photography_lenta_path
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to photography_lenta_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photographies_helper.rb
module PhotographiesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<div class="container">

			<%= form_for @comment do |f| %>

				<p>
					<%= f.label 'comment' %>
					<%= f.text_area :title %>
				</p>

				<%= f.hidden_field :user_id, :value => current_user.id %>

				<p>
					<%= f.submit 'сохранить' %>
				</p>

			<% end %>

</div>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/welcom.html.erb
<h1>Welcom to the Instagram</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/application/navbar' %>
    
    <div class="container">
    
    	<%= yield %>

    </div>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><%= link_to 'My lenta', photography_lenta_path, class: 'nav navbar-nav' %></a></li>
        <li><%= link_to 'My profile', root_path, class: 'nav navbar-nav' %></a></li>
      </ul>
      <ul class="navbar-nav navbar-right">
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><a href="#">View orders</a></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/photographies/index.html.erb
<% if user_signed_in? %>
	<%= image_tag current_user.avatar.url(:medium) %>
	<h6>User:<%= current_user.name %></h6>
	<h6>email:<%= current_user.email %></h6>
	<h1>My photographies</h1>
	<h1><%= link_to 'add photo', new_photography_path %></h1>

	<% @photographies.each do |photography| %>
		<div class="row-1">
		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <h5>Photo title:<img data-src="holder.js/300x200" alt="<%= photography.name %>"></h5>
		      <div class="caption">
				<%= image_tag photography.image.url(:thumb) %>
				<%= photography.get_likes.size%>

				<% if photography.get_likes.size == 1 %>
				    person like this
				<% else %>
				   	people like this
				<% end %>

				<div class="btn-group">

					<% if (current_user.liked? photography) %>
					    <%= link_to unlike_photography_path(photography), method: :put, class: "btn btn-default btn-sm" do %>
						    <span class="glyphicon glyphicon-chevron-down"></span>
						      Unlike
					    <%end %>
					<% else %>
					    <%= link_to like_photography_path(photography), method: :put, class: "btn btn-primary btn-sm" do %>
						    <span class="glyphicon glyphicon-chevron-up"></span>
						      Like
					    <% end %>
					<% end %>
				</div>

				<h2>Author:<%= photography.user.name %></h2>
				<h>Comments:</h>
				<% counter = 1 %>

				<% photography.comments.order(created_at: :desc).each do |comment| %>
					<%= comment.title %>>>>>
					<%= comment.user.name%></br>
					<% counter += 1 %>
					<% if counter == 3 %>
						<% break %>
					<% end %>
				<% end %>

		        <p>...</p>
		        <p>
			        <%= link_to 'delete foto', photography_path(photography), method: :delete, data: {confirm: 'Вы дествительно хотите удалить?'}, class: 'btn btn-primary' %> 
			        <%= link_to 'see comments', photography_path(photography), class: 'btn btn-primary' %>
		        </p>
		      </div>
		    </div>
		  </div>
		</div>
	<% end %>
		
<% else %>
	
	<h1>Welcom to the Instagram</h1>
	<% @users.each do |user| %>	
		<%= user.name %></br>
	<% end %>

<% end %>       

app/views/photographies/lenta.html.erb
<% if user_signed_in? %>

	<div class="columns left-col">
		<%= image_tag current_user.avatar.url(:thumb) %>
		<h6><%= current_user.name %></h6>
		<h6><%= current_user.email %></h6>
		<h1>My lenta</h1>
		<h1><%= link_to 'add photo', new_photography_path %></h1>
		<section>
			<%= render 'shared/stats' %>
		</section>
	</div>

	<div class="columns middle-col">
		<h1>Lenta</h1>
		<% @photographies.each do |photography| %>
			<% if current_user.following?(photography.user) %>
				<%= image_tag photography.user.avatar.url(:thumb) %>
				<h5>Author:<%= photography.user.name %></h5>
				<h5>Photo title:<%= photography.name %></h5>
				<%= image_tag photography.image.url(:thumb) %>
				<%= photography.get_likes.size%>
				<% if photography.get_likes.size == 1 %>
				    person like this
				<% else %>
				   people like this
				<% end %>

				<div class="btn-group">
					<% if (current_user.liked? photography) %>
						<%= link_to unlike_photography_path(photography), method: :put, class: "btn btn-default btn-sm" do %>
						    <span class="glyphicon glyphicon-chevron-down"></span>
						    Unlike
						<%end %>
					<% else %>
					    <%= link_to like_photography_path(photography), method: :put, class: "btn btn-primary btn-sm" do %>
						    <span class="glyphicon glyphicon-chevron-up"></span>
						    Like
					    <% end %>
					<% end %>
				</div>

				<h3>Comments:</h3>
				<% counter = 1 %>
				<% photography.comments.order(created_at: :desc).each do |comment| %>
					<%= comment.title %>>>>>
					<%= comment.user.name%></br>
					<% counter += 1 %>
					<% if counter == 3 %>
						<% break %>
					<% end %>
				<% end %>
		        <p>...</p>
		        <%= link_to 'See comments', photography_path(photography), class: 'btn btn-primary' %>
				<h1>-------------------------------------------------</h1>
			<% end %>
		<% end %>
	</div>

	<div class="columns right-col">
		<% @users.each do |user| %>
			<% unless current_user == user %>
			<%= image_tag user.avatar.url(:thumb) %>
				<h6><%= user.name %></h6>
		
				<div id="follow form">
					<% if current_user.following?(user) %>
						<%= render 'shared/unfollow', user: user.id %>
					<% else %>
						<%= render 'shared/follow', user: user.id %>
					<% end %>
					</br>
				</div>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/photographies/new.html.erb
<div class="container">
	<%= form_for @photography do |f| %>
		<% if @photography.errors.any? %>
			<div class="errors">
				Total errors: <%= @photography.errors.count %>
				<ul>
					<%= @photography.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>	

		<p>
			<%= f.label 'Имя' %><br/>
			<%= f.text_field :name %>
		</p>

		<p>
			<%= f.label 'Изображение фотографа' %><br />
			<%= f.file_field :image %>
		</p>

		<%= f.hidden_field :user_id, :value => current_user.id %>

		<p>
			<%= f.submit 'save' %>
		</p>
	<% end %>
</div>

app/views/photographies/show.html.erb
<div class="container">
	<%= image_tag current_user.avatar.url(:thumb) %>
	<h1>User: <%= current_user.name %></h1>
	<h6><%= current_user.email %></h6>
	<p>------------------------------------------------------------------------------------------------</p>
	<h5>Photo title:<%= @photography.name %></h5>
	<h2><%= image_tag @photography.image.url(:medium) %></h2>
	<h5>Author:<%= @photography.user.name %></h5>
	<%= image_tag @photography.user.avatar.url(:thumb) %>
	<p>------------------------------------------------------------------------------------------------</p>

	<h3>Comments:</h3>

	<% @photography.comments.order(created_at: :desc).each do |comment| %>		
		<%= comment.title %>>>>>>
		<%= comment.user.name %>>>>>>
		<% if @photography.user == current_user %>
			<% if comment.user == current_user %>
	        	<%= link_to 'edit', edit_comment_path(comment) %>
	        <% end %>     
        	<%= link_to 'delete', comment_path(comment), method: :delete, data: {confirm: 'Вы дествительно хотите удалить?'} %>
        <% elsif comment.user == current_user %>
		    <%= link_to 'edit', edit_comment_path(comment) %>     
		    <%= link_to 'delete', comment_path(comment), method: :delete, data: {confirm: 'Вы дествительно хотите удалить?'} %>
	    <% end %>
	    </br>	
	<% end %>

	<div class="container">
		<%= form_for @comment do |f| %>

			<p>
				<%= f.label 'comment' %>
				<%= f.text_area :title %>
			</p>

			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.hidden_field :photography_id, :value => @photography.id %>

			<p>
				<%= f.submit 'сохранить' %>
			</p>

		<% end %>
	</div>
</div>

app/views/shared/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: user)) do |f| %>
	<%= f.hidden_field :followed_id %>
	<%= f.submit 'Follow', class: 'btn btn-large btn-primary' %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%#= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%#= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: user), html: { method: :delete }) do |f| %>
	<%= f.submit 'Unfollow', class: 'btn btn-large' %>
<% end %>